# Generated by Django 4.2.2 on 2023-08-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_alumno_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos/'),
        ),
    ]
