# Generated by Django 4.2.2 on 2023-08-12 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_alumno_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumnos_fotos/'),
        ),
    ]
