# Generated by Django 4.2.2 on 2023-08-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_alter_alumno_descripcion_alter_alumno_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(null=True),
        ),
    ]
