# Generated by Django 4.2.2 on 2023-07-30 23:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_infoextra_ultima_conexion_alter_infoextra_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='ultima_conexion',
        ),
        migrations.AddField(
            model_name='infoextra',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
