# Generated by Django 4.2.2 on 2023-07-30 23:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_infoextra_ultima_conexion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoextra',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
