# Generated by Django 4.2.2 on 2023-07-31 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_infoextra_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='fecha_creacion',
        ),
    ]
