# Generated by Django 4.2.2 on 2023-08-12 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_infoextra_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoextra',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
