# Generated by Django 4.2.2 on 2023-08-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_infoextra_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoextra',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='infoextra',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
